DC = dmd
DFLAGS = -debug -g -od./bin -of./bin/$@ lib/sqlite3.lib

SOURCES = \
	src/cache.d \
	src/config.d \
	src/main.d \
	src/onedrive.d \
	src/sqlite.d \
	src/sync.d \
	src/util.d

onedrive: $(SOURCES)
	$(DC) $(DFLAGS) $(SOURCES)
