name: "Bug Report"
description: Create a Bug Report to help us fix your issue
labels: ["Bug"]
body:
- type: markdown
  attributes:
    value: |
      **Note:**
      Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and compile by using the latest available DMD or LDC compiler. Refer to the the [INSTALL](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) document on how to build the client for your system.
      
- type: textarea
  id: bugDescription
  attributes:
    label: Describe the bug
    description: |
      Add a clear and concise description of what you think the bug is.
  validations:
    required: true