name: "Bug Report"
description: Create a Bug Report to help us fix your issue
labels: ["Bug"]
body:
- type: markdown
  attributes:
    value: |
      **Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and compile by using the latest available DMD or LDC compiler. Refer to the the [INSTALL](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) document on how to build the client for your system.
      
- type: textarea
  id: bugDescription
  attributes:
    label: Describe the bug
    description: |
      Add a clear and concise description of what you think the bug is.
  validations:
    required: true

- type: textarea
  id: operatingSystemDetails
  attributes:
    label: Operating System Details
    description: |
      * What is your Operating System (`uname -a`)
      * Output of: (`cat /etc/redhat-release`) or (`lsb_release -a`)
  validations:
    required: true
    
- type: dropdown
  id: installMethod
  attributes:
    label: Client Installation Method
    description: | 
      How did you install the client?
    multiple: false
    options:
      - Fron Source
      - From Distribution Package
      - From 3rd Party Source (PPA, OpenSuSE Build Service etc)
  validations:
    required: true
    
- type: dropdown
  id: accountType
  attributes:
    label: OneDrive Account Type
    description: |
      What is your OneDrive Account Type?
    multiple: false
    options:
      - Personal
      - Business | Office365
      - SharePoint
  validations:
    required: true

- type: input
  id: applicationVersion
  attributes:
    label: What is your OneDrive Application Version
    description: |
      * What is your 'onedrive' client version (`onedrive --version`)?
  validations:
    required: true
    
- type: textarea
  id: applicationConfig
  attributes:
    label: What is your OneDrive Application Configuration
    description: |
      * What is your Application Configuration (`onedrive --display-config`)?
  validations:
    required: true

- type: textarea
  id: curlVersion
  attributes:
    label: What is your 'curl' version
    description: |
      * What is your output of (`curl --version`)?
  validations:
    required: true
    
- type: dropdown
  id: syncdirLocation
  attributes:
    label: : Where is your 'sync_dir' located
    description: |
      Is your 'sync_dir' a local directory or on a network mount point?
    multiple: false
    options:
      - Local
      - Network
  validations:
    required: true