name: "Feature Request"
description: Suggest an idea for this project
title: "Feature Request: "
labels: ["Feature Request"]
body:
- type: markdown
  attributes:
    value: |
      Suggest an idea for this project
      
- type: textarea
  id: featureProblem
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: |
      A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
  validations:
    required: true
    
- type: textarea
  id: featureSolution
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen.
  validations:
    required: true
    
- type: textarea
  id: featureAlternatives
  attributes:
    label: Describe alternatives you've considered
    description: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
    
- type: textarea
  id: additionalContext
  attributes:
    label: Additional context
    description: |
      Add any other context or information about the feature request here.
  validations:
    required: false