#!/bin/bash

BUILD_DATE=`date "+%Y%m%d%H%M"`

docker build . -t $IMAGE_NAME -f contrib/docker/Dockerfile

docker tag $IMAGE_NAME $DOCKER_REPO:centos7-$BUILD_DATE
docker push $DOCKER_REPO:centos7-$BUILD_DATE

docker build . -t $DOCKER_REPO:stretch -f contrib/docker/Dockerfile-stretch
docker push $DOCKER_REPO:stretch
docker tag $DOCKER_REPO:stretch $DOCKER_REPO:stretch-$BUILD_DATE
docker push $DOCKER_REPO:stretch-$BUILD_DATE

docker build . -t $DOCKER_REPO:alpine -f contrib/docker/Dockerfile-alpine
docker push $DOCKER_REPO:alpine
docker tag $DOCKER_REPO:alpine $DOCKER_REPO:alpine-$BUILD_DATE
docker push $DOCKER_REPO:alpine-$BUILD_DATE
