# -*-Dockerfile-*-
FROM alpine:3.13
RUN apk add \
    alpine-sdk gnupg xz curl-dev sqlite-dev binutils-gold \
    autoconf automake ldc go
RUN go get github.com/tianon/gosu
COPY . /usr/src/onedrive
RUN cd /usr/src/onedrive/ && \
    autoreconf -fiv && \
    ./configure && \
    make clean && \
    make && \
    make install

FROM alpine:3.13
ENTRYPOINT ["/entrypoint.sh"]
RUN apk add --no-cache \
    bash libcurl libgcc shadow sqlite-libs ldc-runtime && \
    mkdir -p /onedrive/conf /onedrive/data
COPY contrib/docker/entrypoint.sh /
COPY --from=0 /root/go/bin/gosu /usr/local/bin/onedrive /usr/local/bin/
