name: onedrive
base: core20
version: '2.4.3-snap1'
summary: Folder synchronization with OneDrive
description: |
  OneDrive is the cloud storage system of Microsoft. This package provides
  the command line client specializing in synchronizing with OneDrive cloud
  storage.
grade: devel
confinement: classic

parts:
  onedrive:
    source: .
    plugin: autotools
    autotools-configure-parameters: 
      - --enable-notifications
      - --enable-completions
    build-packages:
      - build-essential
      - libcurl4-openssl-dev
      - libsqlite3-dev
      - pkg-config
      - git
      - curl
      - libnotify-dev
    build-snaps:
      - dmd
      - dub
    stage-packages:
      - libgcc-s1
      - libglib2.0-0
      - libnotify4
      - libphobos2-ldc-shared90
      - libsqlite3-0
      - init-system-helpers
      - curl
    organize:
      usr/local/bin/onedrive: bin/

apps:
  onedrive:
    command: bin/onedrive
  # service:
  #   command: bin/onedrive --monitor --confdir=$HOME/.config/onedrive
  #   daemon: simple
  #   restart-delay: 3s
  #   restart-condition: on-failure
